name: entityfy_generator
description: Code generator for creating extension methods to map model classes to entity classes using annotations.
version: 2.0.1
homepage: https://github.com/Sirtoolkit/entityfy
repository: https://github.com/Sirtoolkit/entityfy
issue_tracker: https://github.com/Sirtoolkit/entityfy/issues
documentation: https://github.com/Sirtoolkit/entityfy/blob/main/packages/entityfy_generator/README.md

topics:
  - code-generation
  - entity-mapping
  - data-transformation
  - annotations
  - source-gen
  - build-time
  - dev-tools

environment:
  sdk: ^3.8.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  source_gen: ^2.0.0
  build: ^2.5.4
  analyzer: ^7.4.0
  entityfy: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.5.4